# defaults:
#   - _self_
#   - task: libero_10

name: datacollect_diffusion_unet
_target_: diffusion_policy.workspace.transport_datacollect_diffusion_workspace.DatacollectDiffusionWorkspace
checkpoint_dir: null

task_name: transport

horizon: 32
n_obs_steps: 2
n_action_steps: 15
n_latency_steps: 0
past_action_visible: False
keypoint_visible_rate: 1.0

collecting:
  device: "cuda:0"
  seed: 42
  num_episodes: 500  # number of episodes to collect
  render_image: True


hydra:
  job:
    override_dirname: ${name}
  run:
    dir: logs/collect_data/${task_name}/${name}_${task_name}


task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: true
    dataset_path: /pfss/mlde/workspaces/mlde_wsp_MGPATH/VLA/lpb_libero/data/transport/transport_ph_demo_v141_20_perc.hdf5
    horizon: 32
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 20
      obs:
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
    use_cache: true
    val_ratio: 0.0
  dataset_path: /pfss/mlde/workspaces/mlde_wsp_MGPATH/VLA/lpb_libero/data/transport/transport_ph_demo_v141_20_perc.hdf5
  dataset_type: mh
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: true
    crf: 22
    dataset_path: /pfss/mlde/workspaces/mlde_wsp_MGPATH/VLA/lpb_libero/data/transport/transport_ph_demo_v141_20_perc.hdf5
    fps: 10
    max_steps: 700
    n_action_steps: 15
    n_envs: 28
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    render_obs_key: shouldercamera0_image
    shape_meta:
      action:
        shape:
        - 20
      obs:
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
    collect_data: true
  name: transport_image
  shape_meta:
    action:
      shape:
      - 20
    obs:
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
      robot1_eef_pos:
        shape:
        - 3
      robot1_eef_quat:
        shape:
        - 4
      robot1_eye_in_hand_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
      robot1_gripper_qpos:
        shape:
        - 2
      shouldercamera0_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
      shouldercamera1_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb


