_target_: diffusion_policy.workspace.train_pbrl_diffusion_offline_workspace.PbrlDiffusionWorkspace

gamma: 0.999 
pred_action_steps_only: False
checkpoint_dir: null

checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 4
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 32
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: transport_${now:%Y.%m.%d}_${now:%H.%M.%S}_${name}
  project: null
  resume: true
  tags:
  - train_diffusion_unet_hybrid
  - transport_image
  - default
multi_run:
  run_dir: data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_train_diffusion_unet_hybrid_transport_image
  wandb_name_base: ${now:%Y-%m-%d}_${now:%H-%M-%S}_train_diffusion_unet_hybrid_transport_image
n_action_steps: 15
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.pbrl_diffusion_unet_hybrid_image_policy.PbrlDiffusionUnetHybridImagePolicy
  cond_predict_scale: true
  crop_shape:
  - 128
  - 128
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  eval_fixed_crop: true
  horizon: 32
  kernel_size: 5
  n_action_steps: 15
  n_groups: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  shape_meta:
    action:
      shape:
      - 20
    obs:
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
      robot1_eef_pos:
        shape:
        - 3
      robot1_eef_quat:
        shape:
        - 4
      robot1_eye_in_hand_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
      robot1_gripper_qpos:
        shape:
        - 2
      shouldercamera0_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
      shouldercamera1_image:
        shape:
        - 3
        - 140
        - 140
        type: rgb
  beta: 0.01
  bias_reg: 0.25
  bc_coef: 1.0
  ignore_equal_pref: False
  gamma: ${gamma}
  clip_margin: 0.3
  smooth_label: 0.0
  confidence_weight: False
  unclip_win: False

task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: true
    dataset_path: null
    horizon: 32
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 20
      obs:
        rewards:
          shape:
          - 1
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb

    use_cache: true
    val_ratio: 0.0
  dataset_path: null
  dataset_type: mh
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: true
    crf: 22
    dataset_path: null
    fps: 10
    max_steps: 700
    n_action_steps: 15
    n_envs: 10
    n_obs_steps: 2
    n_test: 10
    n_test_vis: 4
    n_train: 0
    n_train_vis: 2
    past_action: false
    render_obs_key: shouldercamera0_image
    shape_meta:
      action:
        shape:
        - 20
      obs:
        rewards:
          shape:
          - 1
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 140
          - 140
          type: rgb
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: transport_image

  task_name: transport
  dense_reward: false
  dataset_1:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    dataset_path: ${training.dataset_2_dir}
    horizon: ${task.dataset.horizon}
    pad_before: ${task.dataset.pad_before}
    pad_after: ${task.dataset.pad_after}
    n_obs_steps: ${task.dataset.n_obs_steps}
    abs_action: ${task.dataset.abs_action}
    rotation_rep: ${task.dataset.rotation_rep}
    use_cache: true
    seed: 42
    val_ratio: ${task.dataset.val_ratio}
    

  dataset_2:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    dataset_path: ${training.dataset_2_dir}
    horizon: ${task.dataset.horizon}
    pad_before: ${task.dataset.pad_before}
    pad_after: ${task.dataset.pad_after}
    n_obs_steps: ${task.dataset.n_obs_steps}
    abs_action: ${task.dataset.abs_action}
    rotation_rep: ${task.dataset.rotation_rep}
    use_cache: true
    seed: 42
    val_ratio: ${task.dataset.val_ratio}
    


  pref_dataset:
    _target_: diffusion_policy.dataset.pbrl_dataset.PbrlDataset
    sequence_length: 100
    val_ratio_data1: 0
    val_ratio_data2: 0
    num_queries: 5
    gamma: ${gamma}
    gpu_device: ${training.device}
    dense_reward: ${task.dense_reward}
    task_name: ${task.name}
    pseudo_preference: True
    feature_extractor: r3m_resnet18
    context_num: 3
    seg_margin: 0.5
    min_progress: 0.0
    n_demos_for_preference: 10

task_name: transport_image
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3000
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1

  cpl_loss_type: 'cplkl'   # 'cpl'
  use_expert_data_1: False
  use_expert_data_2: False
  n_epoch_sft: 0
  sft_type: "pos"
  stride_ratio: 0.5
  pseudo_preference: True
  dataset_1_dir: null
  dataset_2_dir: null
  preference_learning:
    num_rounds: 1
    equal_threshold: 0.05

val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false

# shape_meta:
#   action:
#     shape:
#     - 20
#   obs:
#     rewards:
#       shape:
#       - 1
#     robot0_eef_pos:
#       shape:
#       - 3
#     robot0_eef_quat:
#       shape:
#       - 4
#     robot0_eye_in_hand_image:
#       shape:
#       - 3
#       - 140
#       - 140
#       type: rgb
#     robot0_gripper_qpos:
#       shape:
#       - 2
#     robot1_eef_pos:
#       shape:
#       - 3
#     robot1_eef_quat:
#       shape:
#       - 4
#     robot1_eye_in_hand_image:
#       shape:
#       - 3
#       - 140
#       - 140
#       type: rgb
#     robot1_gripper_qpos:
#       shape:
#       - 2
#     shouldercamera0_image:
#       shape:
#       - 3
#       - 140
#       - 140
#       type: rgb
#     shouldercamera1_image:
#       shape:
#       - 3
#       - 140
#       - 140
#       type: rgb